### ISSUE TITLE
Readme: Install Guide link 404

### ISSUE THREAD

**Issue by pacoxu** [klts-io/kubernetes-lts#154]
### What happened?

NA

### What did you expect to happen?

NA

### How can we reproduce it (as minimally and precisely as possible)?

NA

**Comment by pacoxu** [comment]
of course

**Comment by PrajwalBorkar** [comment]
May I know is that the link not working or should I put another link there and try. because I guess the link page is not available.

**Comment by pacoxu** [comment]
https://klts.io/docs/install/
I think it should be

**Comment by PrajwalBorkar** [comment]
Sure. Both links under the Document section are not working.  And the link u provided is also not working. Others are fine.

![Screenshot (23)](https://user-images.githubusercontent.com/48290911/163125158-113fe659-ae9f-4410-a72c-a60591832b14.png)
![Screenshot (28)](https://user-images.githubusercontent.com/48290911/163125140-3698467c-cebc-4125-a6ff-b691aaf14395.png)

**Comment by pacoxu** [comment]
@PrajwalBorkar 

Both https://klts.io/docs/install/ and https://klts.io/zh/docs/install/ work for me.

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar
> 
> Both https://klts.io/docs/install/ and https://klts.io/zh/docs/install/ work for me.

For me both links showing "This site can’t be reached".

**Comment by wzshiming** [comment]
> > @PrajwalBorkar
> > Both https://klts.io/docs/install/ and https://klts.io/zh/docs/install/ work for me.
> 
> For me both links showing "This site can’t be reached".

It seems that domain name resolution is not working well properly

```
[root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
Server:         103.248.93.5
Address:        103.248.93.5#53

Non-authoritative answer:
klts.io canonical name = klts-io.github.io.
Name:   klts-io.github.io
Address: 185.199.109.153
Name:   klts-io.github.io
Address: 185.199.110.153
Name:   klts-io.github.io
Address: 185.199.111.153
Name:   klts-io.github.io
Address: 185.199.108.153
;; connection timed out; no servers could be reached

[root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
Server:         103.248.93.5
Address:        103.248.93.5#53

Non-authoritative answer:
klts.io canonical name = klts-io.github.io.
Name:   klts-io.github.io
Address: 185.199.110.153
Name:   klts-io.github.io
Address: 185.199.111.153
Name:   klts-io.github.io
Address: 185.199.108.153
Name:   klts-io.github.io
Address: 185.199.109.153
Name:   klts-io.github.io
Address: 2606:50c0:8002::153
Name:   klts-io.github.io
Address: 2606:50c0:8003::153
Name:   klts-io.github.io
Address: 2606:50c0:8001::153
Name:   klts-io.github.io
Address: 2606:50c0:8000::153

[root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
;; connection timed out; no servers could be reached
```

**Comment by PrajwalBorkar** [comment]
Any solution for this issue?

**Comment by PrajwalBorkar** [comment]
> > > @PrajwalBorkar
> > > Both https://klts.io/docs/install/ and https://klts.io/zh/docs/install/ work for me.
> > 
> > 
> > For me both links showing "This site can’t be reached".
> 
> It seems that domain name resolution is not working well properly
> 
> ```
> [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> Server:         103.248.93.5
> Address:        103.248.93.5#53
> 
> Non-authoritative answer:
> klts.io canonical name = klts-io.github.io.
> Name:   klts-io.github.io
> Address: 185.199.109.153
> Name:   klts-io.github.io
> Address: 185.199.110.153
> Name:   klts-io.github.io
> Address: 185.199.111.153
> Name:   klts-io.github.io
> Address: 185.199.108.153
> ;; connection timed out; no servers could be reached
> 
> [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> Server:         103.248.93.5
> Address:        103.248.93.5#53
> 
> Non-authoritative answer:
> klts.io canonical name = klts-io.github.io.
> Name:   klts-io.github.io
> Address: 185.199.110.153
> Name:   klts-io.github.io
> Address: 185.199.111.153
> Name:   klts-io.github.io
> Address: 185.199.108.153
> Name:   klts-io.github.io
> Address: 185.199.109.153
> Name:   klts-io.github.io
> Address: 2606:50c0:8002::153
> Name:   klts-io.github.io
> Address: 2606:50c0:8003::153
> Name:   klts-io.github.io
> Address: 2606:50c0:8001::153
> Name:   klts-io.github.io
> Address: 2606:50c0:8000::153
> 
> [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> ;; connection timed out; no servers could be reached
> ```

Any solution for this issue?

**Comment by wzshiming** [comment]
> > > > @PrajwalBorkar
> > > > Both https://klts.io/docs/install/ and https://klts.io/zh/docs/install/ work for me.
> > > 
> > > 
> > > For me both links showing "This site can’t be reached".
> > 
> > 
> > It seems that domain name resolution is not working well properly
> > ```
> > [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> > Server:         103.248.93.5
> > Address:        103.248.93.5#53
> > 
> > Non-authoritative answer:
> > klts.io canonical name = klts-io.github.io.
> > Name:   klts-io.github.io
> > Address: 185.199.109.153
> > Name:   klts-io.github.io
> > Address: 185.199.110.153
> > Name:   klts-io.github.io
> > Address: 185.199.111.153
> > Name:   klts-io.github.io
> > Address: 185.199.108.153
> > ;; connection timed out; no servers could be reached
> > 
> > [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> > Server:         103.248.93.5
> > Address:        103.248.93.5#53
> > 
> > Non-authoritative answer:
> > klts.io canonical name = klts-io.github.io.
> > Name:   klts-io.github.io
> > Address: 185.199.110.153
> > Name:   klts-io.github.io
> > Address: 185.199.111.153
> > Name:   klts-io.github.io
> > Address: 185.199.108.153
> > Name:   klts-io.github.io
> > Address: 185.199.109.153
> > Name:   klts-io.github.io
> > Address: 2606:50c0:8002::153
> > Name:   klts-io.github.io
> > Address: 2606:50c0:8003::153
> > Name:   klts-io.github.io
> > Address: 2606:50c0:8001::153
> > Name:   klts-io.github.io
> > Address: 2606:50c0:8000::153
> > 
> > [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> > ;; connection timed out; no servers could be reached
> > ```
> 
> Any solution for this issue?

We have updated the DNS configuration. Please try again if you have time.

```
nslookup klts.io 103.248.93.5
Server:         103.248.93.5
Address:        103.248.93.5#53

Non-authoritative answer:
Name:   klts.io
Address: 185.199.108.153
Name:   klts.io
Address: 185.199.109.153
```

**Comment by PrajwalBorkar** [comment]
> > > > > @PrajwalBorkar
> > > > > Both https://klts.io/docs/install/ and https://klts.io/zh/docs/install/ work for me.
> > > > 
> > > > 
> > > > For me both links showing "This site can’t be reached".
> > > 
> > > 
> > > It seems that domain name resolution is not working well properly
> > > ```
> > > [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> > > Server:         103.248.93.5
> > > Address:        103.248.93.5#53
> > > 
> > > Non-authoritative answer:
> > > klts.io canonical name = klts-io.github.io.
> > > Name:   klts-io.github.io
> > > Address: 185.199.109.153
> > > Name:   klts-io.github.io
> > > Address: 185.199.110.153
> > > Name:   klts-io.github.io
> > > Address: 185.199.111.153
> > > Name:   klts-io.github.io
> > > Address: 185.199.108.153
> > > ;; connection timed out; no servers could be reached
> > > 
> > > [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> > > Server:         103.248.93.5
> > > Address:        103.248.93.5#53
> > > 
> > > Non-authoritative answer:
> > > klts.io canonical name = klts-io.github.io.
> > > Name:   klts-io.github.io
> > > Address: 185.199.110.153
> > > Name:   klts-io.github.io
> > > Address: 185.199.111.153
> > > Name:   klts-io.github.io
> > > Address: 185.199.108.153
> > > Name:   klts-io.github.io
> > > Address: 185.199.109.153
> > > Name:   klts-io.github.io
> > > Address: 2606:50c0:8002::153
> > > Name:   klts-io.github.io
> > > Address: 2606:50c0:8003::153
> > > Name:   klts-io.github.io
> > > Address: 2606:50c0:8001::153
> > > Name:   klts-io.github.io
> > > Address: 2606:50c0:8000::153
> > > 
> > > [root@izj6c8zqovyunzghliwu05z admin]# nslookup klts.io 103.248.93.5
> > > ;; connection timed out; no servers could be reached
> > > ```
> > 
> > 
> > Any solution for this issue?
> 
> We have updated the DNS configuration. Please try again if you have time.
> 
> ```
> nslookup klts.io 103.248.93.5
> Server:         103.248.93.5
> Address:        103.248.93.5#53
> 
> Non-authoritative answer:
> Name:   klts.io
> Address: 185.199.108.153
> Name:   klts.io
> Address: 185.199.109.153
> ```

Yeah, now it is working. In the readme, install guide link should be fixed so which link should I add from these two?

**Comment by pacoxu** [comment]
I prefer https://klts.io/docs/install/
